spring:
  profiles:
    active: "@env@"
    ## 允许覆盖同名bean
  main:
    allow-bean-definition-overriding: true
success:
  name: zhangsan
  age: 18
# 日志配置，用以保证SpringBoot就不会在获取配置中心的配置前加载日志配置
# 建议 将日志配置文件的名称设置为logback-spring.xml,这样就可以省去下边这个配置了
logging:
  config: classpath:logback-config.xml
# 自定义属性，用来指定日志文件的存放目录
global:
  logback:
    path: E:/logs/@env@